void setup()
{
  pinMode(6,OUTPUT);
  pinMode(7,OUTPUT);
  pinMode(8,OUTPUT); // Se usaran los pines 6, 7 y 8 de Arduino
}
void loop()
{
      digitalWrite(6,0);
      digitalWrite(7,0);
      digitalWrite(8,0);
      delay(1000);
      digitalWrite(6,0);
      digitalWrite(7,0);
      digitalWrite(8,1);
      delay(1000);
      digitalWrite(6,0);
      digitalWrite(7,1);
      digitalWrite(8,0);
      delay(1000);
      digitalWrite(6,0);
      digitalWrite(7,1);
      digitalWrite(8,1);
      delay(1000);
      digitalWrite(6,1);
      digitalWrite(7,0);
      digitalWrite(8,0);
      delay(1000);
      digitalWrite(6,1);
      digitalWrite(7,0);
      digitalWrite(8,1);
      delay(1000);
      digitalWrite(6,1);
      digitalWrite(7,1);
      digitalWrite(8,0);
      delay(1000);
      digitalWrite(6,1);
      digitalWrite(7,1);
      digitalWrite(8,1);
      delay(1000);
  }
